name: riiaa20
channels:
   - defaults
   - anaconda
   - conda-forge
dependencies:
   - python>=3.7
   - spacy
   - keras
   - nltk
   - numpy
   - scipy
   - pandas
   - matplotlib
   - jupyter
   - scikit-learn
   - pip:
     - tensorflow==2.0.0-beta1
     - tensorflow_probability
     - tensorflow-addons
